### ISSUE TITLE
Error while "Export to URDF"

### ISSUE THREAD

**Issue by drfenixion** [galou/freecad.cross#7]
I press "Export to URDF" and get error. looks wrong path to "wb_globals"

```
18:58:10  Running the Python command 'UrdfExport' failed:
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/FreeCAD/Mod/freecad.cross/freecad/cross/ui/command_urdf_export.py", line 113, in Activated
    xmls.append(obj.Proxy.export_urdf(interactive=True))
  File "/home/ubuntu/.local/share/FreeCAD/Mod/freecad.cross/freecad/cross/robot_proxy.py", line 514, in export_urdf
    p, output_path = get_rel_and_abs_path(self.robot.OutputPath)
  File "/home/ubuntu/.local/share/FreeCAD/Mod/freecad.cross/freecad/cross/wb_utils.py", line 316, in get_rel_and_abs_path
    p = without_ros_workspace(path)
  File "/home/ubuntu/.local/share/FreeCAD/Mod/freecad.cross/freecad/cross/ros/utils.py", line 145, in without_ros_workspace
    from .wb_globals import g_ros_workspace
  File "/tmp/appimage_extracted_962abe530f3b7f573b8341cbc15de676/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)

No module named 'freecad.cross.ros.wb_globals'
```

I use FreeCAD from ROS2 docker container. As i described here [https://github.com/galou/freecad.cross/issues/6](https://github.com/galou/freecad.cross/issues/6)
ROS 2 Iron. FreeCAD 0.21.2

**Comment by drfenixion** [comment]
Resolved by merge
